package com.suam.service;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import com.suam.bean.Assento;
import com.suam.bean.CompraVoo;
import com.suam.bean.Usuario;
import com.suam.bean.Voo;
import com.suam.factory.ConnectionFactory;

public class CompraVooService {

	
	//CREATE TABLE COMPRAVOO(
	//IDCOMPRAVOO INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) NOT NULL,
	//USUARIO_IDUSUARIO INTEGER NOT NULL,
	//VOO_IDVOO INTEGER NOT NULL,
	//PRECO VARCHAR(45) NOT NULL,   ??? COLOCAR NA TABELA VOO?
	//FOREIGN KEY(USUARIO_IDUSUARIO) REFERENCES PUBLIC.USUARIO(IDUSUARIO),
	//FOREIGN KEY(VOO_IDVOO) REFERENCES PUBLIC.VOO(IDVOO));

	
	public static void inserir(CompraVoo compra, Voo voo, Usuario usuario, Assento assento) throws SQLException {
		Connection conexao = ConnectionFactory.getConnection();

		String sql = "INSERT INTO compra VALUES(?,?,00,?,?)";

		try {
			PreparedStatement ps = conexao.prepareStatement(sql);
			ps.setInt(1, usuario.getId());
			ps.setInt(2, voo.getIdVoo());

			ps.execute();
			conexao.commit();
		} catch (SQLException e) {
			conexao.rollback();
			e.printStackTrace();
			throw new SQLException();
		} finally {
			conexao.close();
		}
	}
}
