-- MySQL Script generated by MySQL Workbench
-- Sat Oct 27 18:49:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbWeb2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbWeb2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbWeb2` DEFAULT CHARACTER SET utf8 ;
USE `dbWeb2` ;

-- -----------------------------------------------------
-- Table `dbWeb2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbWeb2`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `dataNascimento` VARCHAR(45) NOT NULL,
  `isAdm` boolean NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbWeb2`.`CartaoCredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbWeb2`.`CartaoCredito` (
  `numeroCartao` INT NOT NULL,
  `dataVencimento` VARCHAR(45) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`numeroCartao`),
  INDEX `fk_CartaoCredito_usuario_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_CartaoCredito_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `dbWeb2`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
